### PR TITLE
Adblock Plus icon support in dark mode (#69)

### PR DESCRIPTION
**Pull request by synapsos**
re #69
I combined the icons into one file so these states could be easily supported:
* Default color in toolbar
* Opacity in panel
* White color in dark mode (`toolbar`, `full` setting respected)
* All of the above when state is diabled (green dot added)
* Default color with opacity in palette (no green dot)

### CODE REVIEW

**Comment by seleznev** [comment]
@0rAX0, you should be careful with files like this. You shouldn't edit them in editors like Inkscape!

@synapsos, do you want to have permissions for push into the main repo? I will can to revert/fix commits what I not like if needed. %) @garrett, are you agree?

**Comment by 0rAX0** [comment]
@seleznev What then, Excel? xD

**Comment by garrett** [comment]
Oh, hey!

So for UI SVGs, it's best to edit in Inkscape, save the source somewhere safe, and export to optimized SVG with decent settings. Be sure to check to make sure the integrity has been preserved (as it's basically lossy SVG, but it can be compelled to look authentic enough). 

BTW: Optimized SVG in Inkscape is a UI to Scour, which can be used from a command-line and on any OS.

The advantage of jumping through this little hoop is that the SVG is usually _much_ smaller in filesize and simpler to render.

**Comment by seleznev** [comment]
@0rAX0, MS Word :P

**Pull request merged**
